var cartoons = [
  {name: "Rocko's Modern Life",
   image: 'https://upload.wikimedia.org/wikipedia/en/0/01/Rocko_title_card.jpg',
   score: 2,
   comments: [{text: "I love this show!", author: "negative Influence"}],
   author: 'Roberto',
   description: "Rocko's Modern Life is an American animated television series created by Joe Murray for Nickelodeon. The series centers on the surreal life of an anthropomorphic Australian-immigrant wallaby named Rocko as well as his friends: the gluttonous steer Heffer, the neurotic turtle Filburt, and Rocko's faithful dog Spunky. It is set in the fictional town of O-Town, and is laden with adult humor, including double entendre, innuendo, and satirical social commentary.",
  },
  {name: "Pokemon",
   image: 'http://3.bp.blogspot.com/_2reYE43DHZE/S6fvYKmxQ4I/AAAAAAAAF-I/uk-Af38lhzQ/s320/pokemon_title.jpg',
   score: 5,
   comments: [],
   author: 'Steve',
   description: 'These cartoon series are accompanied by spin-off programming, consisting of Pokémon Chronicles, a series of side stories featuring characters in the anime that are not its current cast of main characters, and the live action variety and Pokémon-related news shows of Weekly Pokémon Broadcasting Station, Pokémon Sunday, Pokémon Smash!, and Pokémon Get TV, premiering in late 2013.',
  },
  {name: "Animaniacs",
   image: 'http://pre14.deviantart.net/5c7c/th/pre/i/2015/204/4/3/animaniacs_logo_complete_with_shading_by_renardfox-d92itfx.png',
   score: 2,
   comments: [],
   author: 'roberto',
   description: "Animaniacs is an American animated television series, distributed by Warner Bros. Television and produced by Amblin Entertainment and Warner Bros. Animation. Animaniacs is the second animated series produced by the collaboration of Steven Spielberg and Warner Bros. Animation during the animation renaissance of the late 1980s and early 1990s. The studio's first series, Tiny Toon Adventures, was a success among younger viewers, and attracted a sizable number of adult viewers. The Animaniacs writers and animators, led by senior producer Tom Ruegger, used the experience gained from the previous series to create new animated characters that were cast in the mold of Chuck Jones and Tex Avery's creations.",
  },
  {name: "Doug",
   image: 'http://d3vz5f63gip8jk.cloudfront.net/fb_100055_poster.png',
   score: -1,
   comments: [],
   author: 'Dylan',
   description: "Doug is an American animated sitcom created by Jim Jinkins. The show focuses on the early adolescent life of its title character, Douglas \"Doug\" Funnie, who experiences common predicaments while attending school in his new hometown of Bluffington. Doug narrates each story in his journal, and the show incorporates many imagination sequences. The series addresses numerous topics, including trying to fit in, platonic and romantic relationships, self-esteem, bullying, and rumors. Numerous episodes center on Doug's attempts to impress his classmate and crush, Patti Mayonnaise.",
  },
  {name: 'Hey Arnold!',
   image: 'http://multiredtv.com/wp-content/uploads/2014/09/Oye+Arnold.jpg',
   score: 0,
   comments: [],
   author: 'Maria',
   description: "Hey Arnold! is an American animated television series created by Craig Bartlett for Nickelodeon. The show centers on a fourth grader named Arnold, who lives with his grandparents in an inner-city boarding house. Episodes center on his experiences navigating big city life while dealing with the problems he and his friends encounter.",
  },
  {name: "Rugrats",
   image: 'http://www.cool2bkids.com/wp-content/uploads/2015/03/Rugrats.jpg',
   score: 3,
   comments: [],
   author: 'Derek',
   description: "Rugrats gained over 20 awards during its 13-year run, including 4 Daytime Emmy Awards, 6 Kids' Choice Awards, and its own star on the Hollywood Walk of Fame. The series garnered Nickelodeon high ratings and stayed as the network's top rated show for five consecutive years. It was Nickelodeon's longest-running Nicktoon until 2012, when SpongeBob SquarePants aired its 173rd episode.",
  },
  {name: "Captain Planet",
   image: 'http://www.electricfeast.com/wp-content/uploads/2013/05/CaptainPlanetHeader.jpg',
   score: -4,
   comments: [],
   author: 'Anna',
   description: "In February 2009, Mother Nature Network began airing episodes and unreleased footage of Captain Planet and the Planeteers on its website. In September 2010, the Planeteer Movement was launched with the assistance of Pyle as a means for fans of the show to connect and continue to integrate the show's messages into their lives as real-life Planeteers.",
  },
  {name: "The Angry Beavers",
   image: 'https://upload.wikimedia.org/wikipedia/en/7/79/The_Angry_Beavers_title_card.jpg',
   score: 6,
   comments: [{text: "I hate this show, why is it on top?", author: "kid"}, {text: "Everyone has different opinions, I like it...", author: "Cool Guy"}],
   author: 'Roberto',
   description: "The Angry Beavers is an American animated television series created by Mitch Schauer for the Nickelodeon channel. The series revolves around Daggett and Norbert Beaver, two young beaver brothers who have left their home to become bachelors in the forest near the fictional Wayouttatown, Oregon. The show premiered in the United States on April 19, 1997",
  },
  {name: "Ren and Stimpy",
   image: 'https://upload.wikimedia.org/wikipedia/en/7/76/The_Ren_and_Stimpy_Show_Title_Card.jpg',
   score: 1,
   comments: [],
   author: 'Amanda',
   description: "The Ren & Stimpy Show, often simply referred to as Ren & Stimpy, is an American animated television series created by John Kricfalusi for Nickelodeon. The series follows the adventures of titular characters Ren, an emotionally unstable chihuahua, and Stimpy, a good-natured, dimwitted cat.",
  },
  {name: "Duck Tales",
   image: 'https://upload.wikimedia.org/wikipedia/en/4/48/DuckTales_(Main_title).jpg',
   score: 3,
   comments: [],
   author: 'John',
   description: "DuckTales is an Animated television series produced by Disney Television Animation. It premiered on September 18, 1987 and ended on November 28, 1990 with a total of four seasons and 100 episodes.[1][2] An animated theatrical spin-off film based on the series, DuckTales the Movie: Treasure of the Lost Lamp, was released widely in the United States on August 3, 1990. The voice cast from the series reprised their roles for the film.",
  },
  {name: "Recess",
   image: 'http://vignette4.wikia.nocookie.net/90scartoons/images/e/e7/Recess_Title_Card.png/revision/latest?cb=20150715010834',
   score: 0,
   comments: [],
   author: 'Samantha',
   description: "Recess is an American animated television series created by Paul Germain and Joe Ansolabehere (credited as \"Paul and Joe\"). The series focuses on six elementary school students and their interaction with other classmates and teachers. The title refers to the period of time during the school day in which children are not in lessons and are outside in the schoolyard, in North American society. During recess, the children form their own society, complete with government and a class structure, set against the backdrop of a regular school.",
  },
  {name: "X-men",
   image: 'http://www.toplessrobot.com/XMenAnimatedReview1-thumb-300x420-17438.jpg',
   score: 2,
   comments: [],
   author: 'Micka',
   description: "X-Men, also known as X-Men: The Animated Series, is an American animated television series which debuted on October 31, 1992 in the United States on the Fox Network as part of its Fox Kids Saturday morning lineup.[2] X-Men was Marvel Comics' second attempt at an animated X-Men TV series after the pilot X-Men: Pryde of the X-Men was not picked up.",
  },
  {name: "Street Sharks",
   image: 'https://2brokegeeks.files.wordpress.com/2012/03/screen-shot-2012-03-23-at-8-09-06-pm.png',
   score: -1,
   comments: [],
   author: 'Liza',
   description: "Street Sharks was an American-Canadian animated television series about crime-fighting half-man/half-sharks. It was produced by DIC Entertainment and aired from 1994 to 1997, originally as a part of the Amazin' Adventures lineup.[1] Later, in 1996, the Street Sharks teamed up with the Dino Vengers and the show became \"Dino Vengers Featuring Street Sharks\". It was created to promote an existing Mattel toy line of the same name. The creators were David Siegel and Joe Galliani of Mr. Joe's Really Big Productions. Every episode has the word \"Shark\" somewhere in the episode title",
  },
  {name: 'The Magic School Bus',
   image: 'https://upload.wikimedia.org/wikipedia/en/e/e8/The_Magic_School_Bus_title_credit.jpg',
   score: -5,
   comments: [],
   author: 'Mark',
   description: "The Magic School Bus is a Canadian–American Saturday morning animated children's television series, based on the book series of the same name by Joanna Cole and Bruce Degen. It is notable for its use of celebrity talent and combining entertainment with an educational series.[1] Broadcasting & Cable said the show was \"among the highest-rated PBS shows for school-age children.\"[2] On June 10, 2014 Scholastic Media announced that it will be releasing an all-new CG animated series inspired by the original show, entitled \"The Magic School Bus 360°.\" The 26 new half-hour episodes are set to stream on Netflix in 2016.",
 },
]
